FROM node:20-alpine
WORKDIR /app
COPY package.json pnpm-workspace.yaml .npmrc* .pnpmfile.cjs* ./
COPY apps ./apps
COPY packages ./packages
RUN corepack enable && pnpm install --frozen-lockfile
WORKDIR /app/apps/web
RUN pnpm build
CMD ["pnpm", "start"]
